name: Repo Sync to Gitee
on:
  workflow_dispatch:
  schedule:
    - cron: '5 0 * * *'
env:
  # 仓库名称
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  mirror-to-gitee:
    name: Sync to Gitee
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Check if Gitee repository exists and create if not
        run: |
          # 检查 Gitee 仓库是否存在
          response=$(curl -s -o /dev/null -w "%{http_code}" \
            "https://gitee.com/api/v5/repos/cmontage/${{ env.REPO_NAME }}?access_token=${{ secrets.GITEE_PASSWORD }}")
          
          if [ "$response" = "404" ]; then
            echo "仓库不存在，正在创建..."
            # 创建新仓库
            curl -X POST "https://gitee.com/api/v5/user/repos" \
              -H "Content-Type: application/json" \
              -d '{
                "access_token": "${{ secrets.GITEE_PASSWORD }}",
                "name": "${{ env.REPO_NAME }}",
                "description": "Auto-synced from GitHub repository",
                "private": false,
                "has_issues": true,
                "has_wiki": true,
                "can_comment": true
              }'
            echo "仓库创建完成"
          else
            echo "仓库已存在，跳过创建步骤"
          fi
        shell: bash
        
      - name: Mirror repo to Gitee
        uses: abersheeran/sync-gitee-mirror@v1-beta
        with:
          repository: cmontage/${{ env.REPO_NAME }}
          username: cmontage
          password: ${{ secrets.GITEE_PASSWORD }}